### ISSUE TITLE
Question on gene expression patterns correlated with TME cell types.

### ISSUE THREAD

**Issue by zhangyz1997** [Danko-Lab/BayesPrism#31]
I have read the tutorial of the package, and it mentioned that "Correlating Z (after normalization using vst or from bp.res@reference.update@psi_mal) with theta to understand how gene expression of each gene (in malignant cells) correlates with the cell type fraction of non-malignant cells in tumor microenvironment". So should I use the two filters mentioned in the original papers, or use the genes from Z directly?

**Comment by tinyi** [comment]
Thank you for your interest in our methods.

We recommend the use of filters to reduce false positives in the
correlation caused. These false correlations are often caused by cell
states/cell types present in bulk but missing from the single cell
reference. To mitigate this issue, one can 1) select genes overexpressed in
tumor, 2) regress out expression in the query cell type when performing
correlation. Additionally, having multiple cell states for the query cell
type, which helps accounting for the missing cell state issue, may also
improve the inference of gene expression.

**Comment by zhangyz1997** [comment]
I see. Therefore, the result of "get.exp.stat" is exactly what we need in the filtering process. Am I getting it right?

**Comment by tinyi** [comment]
Get.exp.stat will give you the unfiltered expression tensor Z.

**Comment by zhangyz1997** [comment]
I think the "get.exp" function returns Z, but the "gen.exp.stat" function returns the differential expression test result which might be considered as marker genes and used as filters mentioned above?

**Comment by tinyi** [comment]
Ah. You are right. Sorry for the confusion. You may either use get.exp.stat
or perform differential expression analysis using methods like MAST.
