### ISSUE TITLE
Low lymphocyte fraction in lung adenocarcinoma

### ISSUE THREAD

**Issue by WuRAFY** [Danko-Lab/BayesPrism#57]
Firstly, thanks for your tool. Recently I tried BayesPrism to deconvolute LUAD bulk RNA seq data with single cell from same patients as reference. Figure below is the deconvolution result. 
![Rplot](https://github.com/Danko-Lab/BayesPrism/assets/64182733/4bf99cf2-0797-45e2-9833-0fcc4be19164)

The lymphocyte fraction is low. Then I also tried deconvolution on TCGA LUAD and a singapore LUAD datasets. They are all same. Due to few related studied, I doubt if such low lymphocyte fraction cound explain the TIL level in TCGA H&E. Could you please share your related experience on LUAD or other solid tumors?

**Comment by WuRAFY** [comment]
Thanks for your reply. I re-assigned cell type label to each cell then select marks using `select.marker` following the instruction. Then found that there are few markers in some cell types. 
In the FAQ, it is recommended to assign different T cell subtypes with different `cell.type.labels`. But this may also lead to few markers for T cells from different subtypes in my view. Can you give some suggestions?

```
number of markers selected for each cell type: 
malignant :  1668 
club :  22 
AT2 :  93 
basal :  18 
cilited :  362 
AT1 :  81 
plasma :  97 
CD4+ helper T :  1 
CD4+ regulator T :  12 
CD8+ trm :  11 
CD8+ effector T :  9 
CD4+ inhibitory T :  14 
NK :  26 
CD4+ naive T :  3 
B :  67 
macrophage :  136 
neutrophil :  99 
cDC1 :  11 
mast :  61 
monocyte :  98 
cDC2 :  22 
cDC3 :  15 
pDC :  91 
capillary :  58 
lymphatic :  31 
vein/bronchial :  52 
myofibroblast :  86 
pericyte :  66 
advential fibroblast :  7 
mesothelial :  0 
smooth muscle :  39 
alveolar fibroblast :  28 
Proliferating :  118 
```
![T7CFR9OUB%P7{1QP}_X4MC4](https://github.com/Danko-Lab/BayesPrism/assets/64182733/55d07a45-f22e-4c8f-bc64-3e9559964feb)

**Comment by tinyi** [comment]
Hi.

Sorry for the delay.

It seems that indeed there are a bit too few marker genes represented for
some cell type. This might be caused by too few cells in these cell types,
which may give rise to insufficient statistical power when performing
differential expression. Could you check the number of cells in each cell
type? Also, may I ask what  biological samples were your scRNA-seq
reference collected on? It seems to be a lung cancer dataset?

Best,

Tinyi

**Comment by WuRAFY** [comment]
7 lung adenocarcinoma pateints, ~28000 cells in total. To get enough markers, I collapsed multiple cell types. However, the lymphocyte fraction after using markers is still low. 
```
advential fibroblast  alveolar fibroblast                  AT1 
                 300                  107                   77 
                 AT2                    B                basal 
                 253                 2444                  107 
           capillary        CD4+ helper T    CD4+ inhibitory T 
                 161                 1390                  883 
        CD4+ naive T     CD4+ regulator T      CD8+ effector T 
                1955                 1629                 1792 
            CD8+ trm                 cDC1                 cDC2 
                1972                  275                   29 
                cDC3              cilited                 club 
                  27                  258                  221 
           lymphatic           macrophage            malignant 
                  34                  998                 6032 
                mast          mesothelial             monocyte 
                 716                  200                  146 
       myofibroblast           neutrophil                   NK 
                 330                 1680                  318 
                 pDC             pericyte               plasma 
                  24                  269                 2997 
       Proliferating        smooth muscle       vein/bronchial 
                 458                  233                  141 
```
![图片1](https://github.com/Danko-Lab/BayesPrism/assets/64182733/6641f98d-9c80-4861-a771-3fea05469529)

**Comment by tinyi** [comment]
Thank you for your reply. After inspecting your data, I think there are a few issues that may contribute to the seeminlgy underestimated lymphocytes. 

1) I observed that for the marker gene set you provided, it is mostly dominated by malignant cells, whereas lymphocyte markers are much fewer. As BayesPrism infers reads % from each cell over the input gene set, having a fewer number of genes for some cell type will lead to the seemingly underestimated fraction. But this is generally fine as the relative fraction between mixture samples will not be affected. We only need to be cautious when interpreting the absolute fraction (especially to keep in mind when comparing the cell counts%).

If you would like to mitigate this, you may re-compute the markers for each cell type while supplying a cell.type.labels at lower granularity, for example by grouping all T cell subtypes into a T cell, while keeping the cell.state.labels as the way it is. In this way differential expression will not filter out genes commonly expressed in all T cells, and hence will result in more markers for T cells.

2) factors due to the lower total expression  in lymphocytes, as stated in the previous reply.

Hope that this helps.

Best,

Tinyi

**Comment by WuRAFY** [comment]
I have collapsed all T cells into one cell type to find only 61 markers for T cell while malignant cells have 2125. Lymphocyte fraction does not change a lot (still low). But thanks for your help.

At first, we want to find if there is some TME subtypes in LUAD using cell type fraction. But the unbalanced cell combination (low lymphocyte fraction) really worried me. Maybe I can try to centering lymphocyte and other cell fraction across all samples.
```
e.x. subtype 1:  30% fibroblasts + 20% lymphoctyes + 50% myeloid cells
        subtype 2:  20% fibroblasts + 50% lymphoctyes + 30% myeloid cells
```

Thank you for your help.

FY

**Comment by tinyi** [comment]
As explained in the previous reply, the absolute % of cell types requires a careful interpretation. 

I agree with you that for the purpose of subtyping, it is generally recommended to z score each cell type, as it is more desirable to have each cell type (feature) influencing your subtype (clustering) equally, even without the issues discussed above.
