### ISSUE TITLE
optimal number of each cell state

### ISSUE THREAD

**Issue by inofechm** [Danko-Lab/BayesPrism#79]
Hi Tinyi,

Thanks for the amazing package!
I have a large atlas with tens of thousands of each cell state that I use for deconvolution of visium data. 
Sometimes I am getting memory errors even with 400GB.
I was wondering if you could advise on how much to downsample my reference to avoid this (ie. how much of each cell state to keep?) I know the min is 50 but I am wondering if you know what an optimal number is?

Thank you,
Ido

**Comment by tinyi** [comment]
Hi Ido,

Thank you for your interest in our methods. One quick solution is to sum up
the reads in each cell state, and then construct the prism object using
input.type="GEP". But I typically would not recommend using a large number
of cell states where the difference among them is very minor. For cell
types, I would recommend a granularity of having at least 50 or at best
greater than 100 marker genes (differentially expressed genes) if possible.
For cell states it is generally less sensitive to the number of marker
genes, as they will be summed up to represent a cell type. Nevertheless I
would still recommend having sufficient difference to define a cell state,
otherwise it might be more advisable to collapse them into a single state
and improve the sparsity and the signal-to-noise ratio.

Best,

Tinyi

**Comment by inofechm** [comment]
thank you will try GEP.
If I want to keep it using the default approach, is there a number of cells that I could downsample to. Ie. if I have 100000 CD8 T cells, can I downsample the reference to only include 1000 cells?, 10 000? what do you think is optimal?

**Comment by inofechm** [comment]
I just saw that the new version 2.2 supports sparse matrices, which has essentially solved my problem.
Thank you!!
