### ISSUE TITLE
why cell type specific gene expression inference is so much better for cancer cells than for the rest ? 

### ISSUE THREAD

**Issue by Sophon-0** [Danko-Lab/BayesPrism#93]
Hello,
I created a set of pseudo bulk samples and compared the observed versus predicted gene expression for all cell types of the single cell reference. I used 2 single cell data, one for reference and one for creating pseudo bulk. 

The best predicted gene expression is for cancer cells: R>0.6 compared to ground truth. 

Why is the performance so low for other cell types ? R < 0.4 for CD4 T cells 

Is BayesPrism fundamentally designed for cancer cells since there are some signaling pathways involved in the inference ?

**Comment by dankoc** [comment]
Hi,

The approach works the same for both malignant and non-malignant cell types. Performance differences between cell types are mainly driven by the fraction of each cell type in the bulk. Intuitively, for a cell type with a higher number of reads, there's more information in that cell type. This relationship is very visible in Fig. 1h in the BayesPrism paper. (and ofc other factors specific to the quality and match between the reference and bulk will make a difference in overall performance too).

Also, consider using log-Pearson or Spearman as your correlation metric, if you are not already. These metrics tend to be more stable as you are comparing because they are less likely to be driven by a single outlier.

Good luck!
